### ISSUE TITLE
Ask for pretrained models

### ISSUE THREAD

**Issue by StevenShaw1999** [genforce/eqgan#4]
Hello! Sorry to bother you again. I wonder if it would be possible for you to release the pretrained models on FFHQ and LSUN church recently, for I want to do more experiments on basis of your models.
By the way, your codebase and pretrained models help me a lot! Thank you very much!

**Comment by jytime** [comment]
Hi @StevenShaw1999 ,

Thank you for the interest! Please check the freshly baked [model](https://www.dropbox.com/s/q7o3pjb08yev5ex/ffhq.pkl?dl=0) for FFHQ. Its training was completed last night :) The model FID is slightly better than the result in the paper, 2.89 vs 2.96.

I am still dealing with the LSUN Church dataset. Since this code is reorganized for release and different from our original one, we notice a small performance difference in the LSUN Church dataset. I am training it again and expect it could be solved soon.

Best,
Jianyuan

**Comment by StevenShaw1999** [comment]
Thank you for your quick reply and your model! 
Hope everything goes well~

**Comment by jytime** [comment]
@StevenShaw1999 Hi, the model for Church is available now.
